name: JJKUHC
main: me.jjkuhc.Main
version: 1.0
api-version: 1.18
author: Flobill

commands:
  jjk:
    description: "Commande principale de JJK UHC"
    usage: "/jjk <config|sethost>"
    aliases: []
    default: op

  spawn:
    description: "Téléporte au spawn défini"
    usage: "/spawn"

  jump:
    description: "Téléporte au jump défini"
    usage: "/jump"

  setspawn:
    description: "Définit la position du spawn"
    usage: "/setspawn"
    default: op

  setjump:
    description: "Définit la position du jump"
    usage: "/setjump"
    default: op

  gameinfo:
    description: "Affiche l'état actuel de la partie"
    usage: "/gameinfo"

  jjkstart:
    description: "Lancer la partie JJK UHC"
    usage: "/jjkstart"
    permission: jjk.start
    aliases: []

  savestuff:
    description: Sauvegarde le stuff du joueur
    usage: /savestuff

permissions:
  jjk.use:
    description: "Permet d'ouvrir le menu de configuration"
    default: op
